# Generated by Django 6.0.5 on 2026-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_emailverification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="data_bird",
            new_name="birth_date",
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.DeleteModel(
            name="EmailVerification",
        ),
    ]
