# Generated by Django 6.0.5 on 2026-06-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="ico",
            field=models.ImageField(
                blank=True, null=True, upload_to="cat_ico", verbose_name="Иконки"
            ),
        ),
    ]
