# Generated by Django 6.0.5 on 2026-06-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0003_alter_ads_options_category_ico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ads",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="response",
            name="is_accepted",
            field=models.IntegerField(default=0, verbose_name="Принят"),
        ),
    ]
