# Generated by Django 6.0.5 on 2026-07-15 07:35

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def merge_duplicate_responses(apps, schema_editor):
    """Preserve old response texts before enforcing one response per ad."""
    response_model = apps.get_model("ads", "Response")
    duplicate_groups = (
        response_model.objects.values("author_id", "ads_id")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )

    for group in duplicate_groups.iterator():
        responses = list(
            response_model.objects.filter(
                author_id=group["author_id"],
                ads_id=group["ads_id"],
            ).order_by("-is_accepted", "created_at", "id")
        )
        keeper, *duplicates = responses
        texts = [response.text.strip() for response in responses if response.text.strip()]
        keeper.text = "\n\n---\n\n".join(dict.fromkeys(texts))
        keeper.save(update_fields=["text"])
        response_model.objects.filter(id__in=[response.id for response in duplicates]).delete()

    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):
    dependencies = [
        ("ads", "0004_alter_ads_is_published_alter_response_is_accepted"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ads",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
            },
        ),
        migrations.AlterField(
            model_name="ads",
            name="content",
            field=models.TextField(verbose_name="Содержимое объявления"),
        ),
        migrations.AlterField(
            model_name="ads",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="category",
            name="ico",
            field=models.ImageField(
                blank=True, null=True, upload_to="cat_ico", verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="is_accepted",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Ожидает ответа"), (1, "Отклонён"), (2, "Принят")],
                db_index=True,
                default=0,
                verbose_name="Статус",
            ),
        ),
        migrations.RunPython(merge_duplicate_responses, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("author", "ads"), name="unique_response_per_author_and_ad"
            ),
        ),
    ]
